### ISSUE TITLE
Investigate data normalization and denormalization

### ISSUE THREAD

**Issue by sjvrijn** [ESI-FAR/TeSoPs-ELECTRIcity_NILM#2]
The dataset is normalized before training. The denormalization does not result in the same order of magnitude of data. Why?

**Comment by OleMussmann** [comment]
Training for the current batch happened with the normalization method "mean". This means subtracting the mean from the data, and then dividing it by the standard deviation. However, the data is not normally distributed, and strongly not so. This means your `mean` and `std` are very dependent on how many "peaks" there are in the data. We found the reason for the discrepancy in ranges of training- and inference-data. Closing this issue, the fix will be implemented in the scope of #10 .
