### ISSUE TITLE
Use Zenodo

### ISSUE THREAD

**Issue by OleMussmann** [ESI-FAR/TeSoPs-ELECTRIcity_NILM#35]

**Comment by sjvrijn** [comment]
Zenodo has been enabled:
![image](https://github.com/ESI-FAR/TeSoPs-ELECTRIcity_NILM/assets/8833517/49f2b08a-188e-4f71-a84d-e8ee3038fe33)

Should now activate automatically upon first release #32

**Comment by sjvrijn** [comment]
See #18 for more details
